language: c

branches:
  only:
    - master

notifications:
  email: false

before_script:
  - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz -O - | tar xz
  - cd SDL2-2.0.5 && ./configure && make && sudo make install && cd ..

script:
  - ./autogen.sh && ./configure && make
